name: BUILD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodule init
      run: git submodule update --init --recursive
    - name: make
      run: make all
    - name: make clean
      run: make clean
    - name: make fclean
      run: make fclean
    - name: make re
      run: make re
